config/routes.rb
Rails.application.routes.draw do
	root  'books#index'
  devise_for :users
  resources :books do
	resources :reviews
  end		
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :reviews
	
	mount_uploader :picture, PictureUploader
	validates :name, :presence => true
end	

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :book

	validates :description, :presence => true
end	

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @books = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:author, :name, :description, :picture)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@book = Book.find(params[:book_id])
		@review = @book.reviews.new
	end

	def create
      @book = Book.find(params[:book_id])
      @review = @book.reviews.new(review_params)
      if @review.save
        redirect_to book_path(@review.book)
      else
        render :new
      end
  end

  def edit
    @book = Book.find(params[:book_id])
    @review = @book.reviews.find(params[:id])
   
 end

def update
   @book = Book.find(params[:book_id])
   @review = @book.reviews.find(params[:id])
   if @review.update(review_params)
     flash[:notice] = "Review successfully updated!"
     redirect_to book_path(@book)
   else
     render :edit
   end
 end

def destroy
   @book = Book.find(params[:book_id])
   @review = @book.reviews.find(params[:id])
   @review.destroy
   flash[:notice] = "Review successfully deleted!"
   redirect_to book_path(@book)
 end

  private
    def review_params
      params.require(:review).permit(:description)
    end

end		

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
	<%= f.label :author %>
	<%= f.text_field :author %>	

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :picture %>
    <%= f.file_field :picture %>

    <%= f.submit %>
  <% end %>

app/views/books/edit.html.erb
<h1>Edit Book Details</h1>

<%= render 'form' %>

app/views/books/index.html.erb
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">BookCLUB</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">About</a></li>
        <li><a href="badges.html">Library</a></li>
        

        <% if user_signed_in? %>
          <li><%= link_to "Sign-Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign-In", new_user_session_path,method: :get %></li>
        <% end %> 


      </ul>
    </div>
  </nav>

<h2> This Weeks Bestseller list</h2>
<hr />
<div class="carousel">
    <a class="carousel-item" ><img src="https://prodimage.images-bn.com/pimages/9780385543026_p0_v4_s460x700.jpg"></a>
    <a class="carousel-item" ><img src="https://prodimage.images-bn.com/pimages/9781250077011_p0_v8_s460x700.jpg"></a>
    <a class="carousel-item" ><img src="http://prodimage.images-bn.com/pimages/9781455591749_p0_v6_s192x300.jpg"></a>
    <a class="carousel-item" ><img src="https://prodimage.images-bn.com/pimages/9781476789385_p0_v2_s460x700.jpg"></a>
    <a class="carousel-item" ><img src="https://prodimage.images-bn.com/pimages/9781616205676_p0_v4_s461x700.jpg"></a>
    <a class="carousel-item" ><img src="https://prodimage.images-bn.com/pimages/9781250066190_p0_v3_s460x700.jpg"></a> 
    <a class="carousel-item" ><img src="https://prodimage.images-bn.com/pimages/9780316262330_p0_v7_s.jpg"></a>
    <a class="carousel-item" ><img src="https://prodimage.images-bn.com/pimages/9780345543882_p0_v2_s461x700.jpg"></a> 
    <a class="carousel-item" ><img src="https://prodimage.images-bn.com/pimages/9781455569021_p0_v4_s460x700.jpg"></a> 5
    <a class="carousel-item" ><img src="https://prodimage.images-bn.com/pimages/9781250051042_p0_v1_s461x700.jpg"></a>
    <a class="carousel-item" ><img src="https://s-media-cache-ak0.pinimg.com/236x/ce/bf/1d/cebf1db1bfef84b35f7879a2a6395fe1.jpg"></a>
  </div>

<h1> Book of the Week </h1>


<ul class= "book">

<% @books.each do |book| %>
	<h3><li><%= link_to book.name, book_path(book)%></li></h3>
  <p><%= image_tag book.picture_url.to_s, style:"width:192px; height:292px;", class:"img-circle" %></p>
<% end %>

<%= link_to "New Book", new_book_path %>

</ul> 

app/views/books/new.html.erb
<h1> Add New Book </h1>

<%= render 'form' %>	

app/views/books/show.html.erb
<h1> <%= @book.name %> </h1>

<hr />

<p><%= image_tag @book.picture_url.to_s, style:"width:192px; height:292px;", class:"img-circle" %></p>

<h4><%= @book.description %></h4>



<% if @book.reviews.any? %>
	<h4>Here are the reviews for this book</h4>
	<ul>
		<% @book.reviews.each do |review| %>
		<li>
			<%= review.description %>
			<%= link_to "Edit", edit_book_review_path(@book, review) %>
			<%= link_to "Delete", book_review_path(@book, review),
									:data => {:confirm => "Are you sure?",
										:method => "delete"} %>
		</li>
		<% end %>
	</ul>
<% else %>
	<p> There are no reviews yet add your OWN now!!</p>
<% end %>

<%= link_to "Add a review", new_book_review_path(@book) %>
			





<p><%= link_to "Edit", edit_book_path(@book)%></p>



 
<p><%= link_to "Delete", book_path(@book),
                           :data => {:confirm => "You sure?",
                                     :method => "delete"} %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookclub</title>

    <%= csrf_meta_tags %>
   

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

 <!-- Compiled and minified CSS -->
  
  </head>

  <body>

  
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for [@book, @review] do |f| %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.submit %>
<% end %>	

app/views/reviews/edit.html.erb
<h1> Edit review for <%= @book.name %> </h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h1> New review for <%= @book.name %> </h1>

<%= render 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>